label_to_idx = {'13': 0,
                '8': 1,
                '14': 2,
                'P1-1': 3,
                '6': 4,
                '10': 5,
                '9': 6,
                '34': 7,
                '11': 8,
                '5': 9,
                '2': 10,
                '3': 11,
                '39': 12,
                '38': 13,
                'P4-4': 14,
                '18': 15,
                'P1-3': 16,
                'P4-2': 17,
                'P7-4': 18,
                '12': 19,
                'P7-2': 20,
                '7': 21,
                '46': 22,
                '15': 23,
                '17': 24,
                '4': 25,
                'P1-2': 26,
                'P7-1': 27,
                'P3-1': 28,
                'P7-5': 29,
                'P12-1': 30,
                'P6-3': 31,
                'P7-3': 32}

idx_to_article = ['Right to an effective remedy',
                  'Right to respect for private and family life',
                  'Prohibition of discrimination',
                  'Protection of property',
                  'Right to a fair trial',
                  'Freedom of expression',
                  'Freedom of thought, conscience and religion',
                  'Individual applications',
                  'Freedom of assembly and association',
                  'Right to liberty and security',
                  'Right to life',
                  'Prohibition of torture',
                  'Friendly settlements',
                  'Examination of the case',
                  'Prohibition of collective expulsion of aliens',
                  'Limitation on use of restrictions on rights',
                  'Right to free elections',
                  'Freedom of movement',
                  'Right not to be tried or punished twice',
                  'Right to marry',
                  'Right of appeal in criminal matters',
                  'No punishment without law',
                  'Binding force and execution of judgments',
                  'Derogation in time of emergency',
                  'Prohibition of abuse of rights',
                  'Prohibition of slavery and forced labour',
                  'Right to education',
                  'Procedural safeguards relating to expulsion of aliens',
                  'Right to elections',
                  'Equality between spouses',
                  'General prohibition of discrimination',
                  'Prohibition of derogations',
                  'Compensation for wrongful conviction',
                  'Unclear']